if(RK_DEPS_RPLIDAR_FOUND)
    add_executable(rplidar_demo demos/lidar/rplidar_demo.cpp)
    add_executable(rplidar_timed_demo demos/lidar/rplidar_timed_demo.cpp)
    add_executable(rplidar_guard_demo demos/lidar/rplidar_guard_demo.cpp)
    add_executable(rplidar_fov_filter_demo demos/lidar/rplidar_fov_filter_demo.cpp)
    target_link_libraries(rplidar_demo PRIVATE rk_lidar)
    target_link_libraries(rplidar_timed_demo PRIVATE rk_lidar)
    target_link_libraries(rplidar_guard_demo PRIVATE rk_lidar)
    target_link_libraries(rplidar_fov_filter_demo PRIVATE rk_lidar)
endif()
