if(RK_DEPS_RGA_FOUND AND RK_DEPS_RKNN_FOUND)
    add_executable(stream_gateway_app apps/stream_gateway_main.cpp)
    target_link_libraries(stream_gateway_app PRIVATE rk_pipeline)
    add_executable(camera_rga_rknn_rtsp_demo ALIAS stream_gateway_app)
endif()
