#!/usr/bin/env python3
"""Gate PhaseC metrics with configurable thresholds.

This script reads metrics_table.csv generated by analyze_phasec_metrics.py
and checks whether each scene meets target thresholds.

Exit codes:
- 0: all checked scenes passed
- 1: at least one checked scene failed
- 2: invalid input or missing files
"""

import argparse
import csv
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple


@dataclass
class GateThresholds:
    retention_min: float
    id_switch_max: float
    fragmentation_max: float
    latency_p95_max_ms: float
    jitter_std_max_m: float
    jitter_span_max_m: float


def safe_float(value: str) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return float("nan")


def load_rows(csv_path: Path) -> List[Dict[str, str]]:
    rows: List[Dict[str, str]] = []
    with csv_path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if not row:
                continue
            rows.append(row)
    return rows


def fmt(v: float, digits: int = 3) -> str:
    if math.isnan(v):
        return "nan"
    return f"{v:.{digits}f}"


def check_scene(scene: str, row: Dict[str, str], t: GateThresholds) -> Tuple[bool, List[str]]:
    reasons: List[str] = []

    retention = safe_float(row.get("track_retention_ratio", ""))
    id_switch = safe_float(row.get("id_switch_proxy_rate", ""))
    frag = safe_float(row.get("track_fragmentation_rate", ""))
    p95 = safe_float(row.get("latency_p95_ms", ""))
    jitter_std = safe_float(row.get("distance_jitter_std_m", ""))
    jitter_span = safe_float(row.get("distance_jitter_p95_p5_m", ""))

    if math.isnan(retention) or retention < t.retention_min:
        reasons.append(f"retention {fmt(retention)} < {fmt(t.retention_min)}")
    if math.isnan(id_switch) or id_switch > t.id_switch_max:
        reasons.append(f"id_switch {fmt(id_switch)} > {fmt(t.id_switch_max)}")
    if math.isnan(frag) or frag > t.fragmentation_max:
        reasons.append(f"fragmentation {fmt(frag)} > {fmt(t.fragmentation_max)}")
    if math.isnan(p95) or p95 > t.latency_p95_max_ms:
        reasons.append(f"latency_p95_ms {fmt(p95)} > {fmt(t.latency_p95_max_ms)}")

    # Jitter checks are strict only for static_target; for other scenes they are advisory.
    if scene == "static_target":
        if math.isnan(jitter_std) or jitter_std > t.jitter_std_max_m:
            reasons.append(f"jitter_std_m {fmt(jitter_std)} > {fmt(t.jitter_std_max_m)}")
        if math.isnan(jitter_span) or jitter_span > t.jitter_span_max_m:
            reasons.append(f"jitter_span_m {fmt(jitter_span)} > {fmt(t.jitter_span_max_m)}")

    return len(reasons) == 0, reasons


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Gate PhaseC metrics with thresholds")
    p.add_argument("--run-dir", default="", help="PhaseC run directory (contains metrics_table.csv)")
    p.add_argument("--metrics-csv", default="", help="Path to metrics_table.csv")

    p.add_argument("--retention-min", type=float, default=0.70)
    p.add_argument("--id-switch-max", type=float, default=0.20)
    p.add_argument("--fragmentation-max", type=float, default=0.60)
    p.add_argument("--latency-p95-max-ms", type=float, default=180.0)
    p.add_argument("--jitter-std-max-m", type=float, default=0.50)
    p.add_argument("--jitter-span-max-m", type=float, default=1.50)

    p.add_argument(
        "--require-scenes",
        default="static_target,approaching_target,crossing_occlusion",
        help="Comma-separated required scenes",
    )
    return p.parse_args()


def resolve_csv(args: argparse.Namespace) -> Path:
    if args.metrics_csv:
        return Path(args.metrics_csv)
    if args.run_dir:
        return Path(args.run_dir) / "metrics_table.csv"
    return Path("")


def main() -> int:
    args = parse_args()
    csv_path = resolve_csv(args)
    if not str(csv_path) or not csv_path.is_file():
        print(f"error: metrics csv not found: {csv_path}")
        return 2

    rows = load_rows(csv_path)
    if not rows:
        print(f"error: no rows in csv: {csv_path}")
        return 2

    thresholds = GateThresholds(
        retention_min=args.retention_min,
        id_switch_max=args.id_switch_max,
        fragmentation_max=args.fragmentation_max,
        latency_p95_max_ms=args.latency_p95_max_ms,
        jitter_std_max_m=args.jitter_std_max_m,
        jitter_span_max_m=args.jitter_span_max_m,
    )

    required_scenes = [s.strip() for s in args.require_scenes.split(",") if s.strip()]
    by_scene = {row.get("scene", "").strip(): row for row in rows}

    missing = [s for s in required_scenes if s not in by_scene]
    if missing:
        print("error: missing scenes: " + ", ".join(missing))
        return 2

    failures = 0
    print("[phasec_gate]")
    for scene in required_scenes:
        ok, reasons = check_scene(scene, by_scene[scene], thresholds)
        if ok:
            print(f"PASS {scene}")
        else:
            failures += 1
            print(f"FAIL {scene}: " + "; ".join(reasons))

    if failures == 0:
        print("RESULT: PASS")
        return 0

    print(f"RESULT: FAIL ({failures} scene(s))")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
