add_library(rk_video_publish_webrtc STATIC src/video/webrtc_publisher.cpp)
target_include_directories(rk_video_publish_webrtc PUBLIC ${CMAKE_SOURCE_DIR}/include)
target_link_libraries(rk_video_publish_webrtc PUBLIC rk_video_base)
if(RK_DEPS_ZLM_FOUND)
    target_include_directories(rk_video_publish_webrtc PUBLIC ${ZLM_API_INCLUDE_DIR})
endif()
